### PR TITLE
core: delete unnecessary files

### PR DESCRIPTION
**Pull request by alisd23**

### CODE REVIEW

**Comment by chrisprice** [comment]
Don't we need the .babelrc for the tests? Also shouldn't the .eslintrc point to the d3fc-scripts version so that editors can pick it up?

**Comment by alisd23** [comment]
We shouldn't need the `.babelrc` for tests, as I can't see anywhere in d3fc-scripts which uses it. But yes the `.eslint` should stay, my bad

**Comment by chrisprice** [comment]
I believe it's used by `babel-register`...

**Comment by alisd23** [comment]
Shouldn't that use the .bablerc in d3fc-scripts? Or is that just for build?

**Comment by chrisprice** [comment]
I actually don't know how it works...

**Comment by ColinEberhardt** [comment]
d3fc-scripts uses the following babel config for bundling

```
        babel({
            babelrc: false,
            presets: ['es2015-rollup']
        }),
```

so doesn't use a `.babelrc` - jasmine depends on this same code, so I don't see a need for any `.babelrc` files ... anywhere.

I do recall previously that we needed a different set of presets for jasmine, which was being run without bundling. However, that isn't the way it works anymore!

**Comment by alisd23** [comment]
Failed sad face :-1:. Looks like it does need the `babelrc`, but where?

**Pull request closed without merging**
